ALTER TABLE instructions ADD COLUMN agent TEXT DEFAULT NULL;
ALTER TABLE instructions ADD COLUMN parallel INTEGER NOT NULL DEFAULT 0;
ALTER TABLE instructions ADD COLUMN actor TEXT NOT NULL DEFAULT 'agent';
